# Generated by Django 4.2.7 on 2023-11-23 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositBaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField(null=True)),
                ('fin_co_no', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.TextField(null=True)),
                ('dcls_end_day', models.TextField(null=True)),
                ('fin_co_subm_day', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cur_unit', models.TextField()),
                ('ttb', models.TextField()),
                ('tts', models.TextField()),
                ('deal_bas_r', models.TextField()),
                ('bkpr', models.TextField()),
                ('yy_efee_r', models.TextField()),
                ('ten_dd_efee_r', models.TextField()),
                ('kftc_bkpr', models.TextField()),
                ('kftc_deal_bas_r', models.TextField()),
                ('cur_nm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaveBaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField(null=True)),
                ('fin_co_no', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.TextField(null=True)),
                ('dcls_end_day', models.TextField(null=True)),
                ('fin_co_subm_day', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveOptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('rsrv_type', models.TextField(null=True)),
                ('rsrv_type_nm', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('baselist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.savebaselist')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('baselist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.depositbaselist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
